package com.example.vm.guest.os

enum class InstallationMode {
    MODE_A_PREINSTALLED, // Pre-installed cloud image (.img, .qcow2, .raw)
    MODE_B_ISO_INSTALLER  // Installer ISO (.iso)
}

/**
 * Typed OS Manifest model for official, legitimate guest operating system images.
 * Adheres strictly to open-source licensing and official distribution infrastructure.
 */
data class OSManifest(
    val id: String,
    val name: String,
    val version: String,
    val osCategory: String, // "Ubuntu", "Kali Linux", "Debian", "Alpine", "Fedora", "AlmaLinux", "Rocky Linux", "Arch Linux", "openSUSE", "Custom"
    val architecture: String = "ARM64 (aarch64)",
    val format: String = "IMG", // "IMG" or "ISO"
    val installationMode: InstallationMode = InstallationMode.MODE_A_PREINSTALLED,
    val sourceName: String,
    val sourceUrl: String,
    val kernelUrl: String = "",
    val initramfsUrl: String = "",
    val diskUrl: String = "",
    val expectedKernelSha256: String = "",
    val expectedInitramfsSha256: String = "",
    val expectedDiskSha256: String = "",
    val downloadSizeBytes: Long,
    val recommendedRamMb: Int = 2048,
    val minimumStorageGb: Int = 10,
    val defaultKernelCmdline: String = "console=ttyAMA0,115200 root=/dev/vda1 rw earlycon=pl011,0x09000000 init=/init",
    val consoleDevice: String = "ttyAMA0 (PL011 UART)",
    val defaultUser: String = "ubuntu",
    val defaultPassword: String = "ubuntu",
    val compatibilityStatus: String = "Verified for MobileVM ARM64 Engine",
    val isBootSupported: Boolean = true,
    val licenseName: String = "GPL-2.0 / Open Source",
    val licenseUrl: String = "",
    val copyrightNotice: String = "",
    val notes: String = ""
)

object OSManifestRegistry {

    val OFFICIAL_MANIFESTS: List<OSManifest> = listOf(
        // --- UBUNTU ---
        OSManifest(
            id = "ubuntu-24-04-cloud-arm64",
            name = "Ubuntu 24.04 LTS (Cloud Image)",
            version = "24.04 LTS (Noble Numbat)",
            osCategory = "Ubuntu",
            architecture = "ARM64 (aarch64)",
            format = "IMG",
            installationMode = InstallationMode.MODE_A_PREINSTALLED,
            sourceName = "Official Canonical Cloud Infrastructure",
            sourceUrl = "https://cloud-images.ubuntu.com/releases/24.04/release/",
            kernelUrl = "https://cloud-images.ubuntu.com/releases/noble/release/unpacked/ubuntu-24.04-server-cloudimg-arm64-vmlinuz-generic",
            initramfsUrl = "https://cloud-images.ubuntu.com/releases/noble/release/unpacked/ubuntu-24.04-server-cloudimg-arm64-initrd-generic",
            diskUrl = "https://cloud-images.ubuntu.com/releases/noble/release/ubuntu-24.04-server-cloudimg-arm64.img",
            expectedKernelSha256 = "71fe6776ef591ea452661a5933e11d2044c5df6aaf76cf39b8d9655fa4e47904",
            expectedInitramfsSha256 = "f77f65eccd619be537e44a7bb2664048e27f20fc8c8e7d4eeb5cf63d0c8cd213",
            downloadSizeBytes = 48L * 1024L * 1024L,
            recommendedRamMb = 2048,
            minimumStorageGb = 16,
            defaultKernelCmdline = "console=ttyAMA0,115200 root=/dev/vda1 rw earlycon=pl011,0x09000000 init=/init",
            consoleDevice = "ttyAMA0 (PL011 UART)",
            defaultUser = "ubuntu",
            defaultPassword = "ubuntu",
            compatibilityStatus = "Pre-installed Cloud Image — Verified ARM64 Boot",
            isBootSupported = true,
            licenseName = "GPL-2.0 / Canonical Distribution License",
            licenseUrl = "https://ubuntu.com/legal",
            copyrightNotice = "© Canonical Ltd. Ubuntu is a registered trademark of Canonical Ltd.",
            notes = "Official Canonical Ubuntu 24.04 ARM64 Cloud Image. Bootable via direct kernel boot or cloud-init."
        ),
        OSManifest(
            id = "ubuntu-24-04-iso-arm64",
            name = "Ubuntu 24.04 LTS (Installer ISO)",
            version = "24.04 LTS (Noble Numbat)",
            osCategory = "Ubuntu",
            architecture = "ARM64 (aarch64)",
            format = "ISO",
            installationMode = InstallationMode.MODE_B_ISO_INSTALLER,
            sourceName = "Official Canonical CD Mirror",
            sourceUrl = "https://cdimage.ubuntu.com/releases/24.04/release/",
            diskUrl = "https://cdimage.ubuntu.com/releases/24.04/release/ubuntu-24.04-live-server-arm64.iso",
            downloadSizeBytes = 2200L * 1024L * 1024L,
            recommendedRamMb = 2048,
            minimumStorageGb = 20,
            defaultKernelCmdline = "console=ttyAMA0,115200 earlycon=pl011,0x09000000",
            consoleDevice = "ttyAMA0 (PL011 UART)",
            defaultUser = "ubuntu",
            defaultPassword = "ubuntu",
            compatibilityStatus = "Installer ISO — Mode B Virtual CD-ROM Boot",
            isBootSupported = true,
            licenseName = "GPL-2.0 / Canonical Distribution License",
            licenseUrl = "https://ubuntu.com/legal",
            copyrightNotice = "© Canonical Ltd. Ubuntu is a registered trademark of Canonical Ltd.",
            notes = "Official Ubuntu ARM64 Live Server Installer ISO. Boots CD-ROM first to install OS onto virtual disk."
        ),

        // --- KALI LINUX ---
        OSManifest(
            id = "kali-2024-cloud-arm64",
            name = "Kali Linux 2024 (Generic Cloud Image)",
            version = "2024.3 (Security OS)",
            osCategory = "Kali Linux",
            architecture = "ARM64 (aarch64)",
            format = "IMG",
            installationMode = InstallationMode.MODE_A_PREINSTALLED,
            sourceName = "Official Kali Linux Release Infrastructure",
            sourceUrl = "https://cdimage.kali.org/current/",
            kernelUrl = "https://cloud-images.ubuntu.com/releases/noble/release/unpacked/ubuntu-24.04-server-cloudimg-arm64-vmlinuz-generic",
            initramfsUrl = "https://cloud-images.ubuntu.com/releases/noble/release/unpacked/ubuntu-24.04-server-cloudimg-arm64-initrd-generic",
            diskUrl = "https://cdimage.kali.org/current/kali-linux-2024.3-cloud-generic-arm64.img",
            expectedKernelSha256 = "71fe6776ef591ea452661a5933e11d2044c5df6aaf76cf39b8d9655fa4e47904",
            expectedInitramfsSha256 = "f77f65eccd619be537e44a7bb2664048e27f20fc8c8e7d4eeb5cf63d0c8cd213",
            downloadSizeBytes = 48L * 1024L * 1024L,
            recommendedRamMb = 2048,
            minimumStorageGb = 20,
            defaultKernelCmdline = "console=ttyAMA0,115200 root=/dev/vda1 rw earlycon=pl011,0x09000000 init=/init",
            consoleDevice = "ttyAMA0 (PL011 UART)",
            defaultUser = "kali",
            defaultPassword = "kali",
            compatibilityStatus = "Pre-installed Cloud Image — Verified ARM64 Boot",
            isBootSupported = true,
            licenseName = "GPL-3.0 / OffSec Distribution License",
            licenseUrl = "https://www.kali.org/about-us/",
            copyrightNotice = "© OffSec Services Limited. Kali Linux is a registered trademark.",
            notes = "Official OffSec Kali Linux ARM64 Cloud Image. Includes penetration testing userland utilities."
        ),
        OSManifest(
            id = "kali-2024-iso-arm64",
            name = "Kali Linux 2024 (Installer ISO)",
            version = "2024.3 (Installer)",
            osCategory = "Kali Linux",
            architecture = "ARM64 (aarch64)",
            format = "ISO",
            installationMode = InstallationMode.MODE_B_ISO_INSTALLER,
            sourceName = "Official Kali Linux CD Mirror",
            sourceUrl = "https://cdimage.kali.org/current/",
            diskUrl = "https://cdimage.kali.org/current/kali-linux-2024.3-installer-arm64.iso",
            downloadSizeBytes = 3400L * 1024L * 1024L,
            recommendedRamMb = 2048,
            minimumStorageGb = 32,
            defaultKernelCmdline = "console=ttyAMA0,115200 earlycon=pl011,0x09000000",
            consoleDevice = "ttyAMA0 (PL011 UART)",
            defaultUser = "kali",
            defaultPassword = "kali",
            compatibilityStatus = "Installer ISO — Mode B Virtual CD-ROM Boot",
            isBootSupported = true,
            licenseName = "GPL-3.0 / OffSec Distribution License",
            licenseUrl = "https://www.kali.org/about-us/",
            copyrightNotice = "© OffSec Services Limited. Kali Linux is a registered trademark.",
            notes = "Official Kali Linux ARM64 Installer ISO. Boots CD-ROM first to install full Kali toolkit onto virtual disk."
        ),

        // --- DEBIAN ---
        OSManifest(
            id = "debian-12-arm64",
            name = "Debian 12 ARM64 (Cloud Image)",
            version = "12 (Bookworm)",
            osCategory = "Debian",
            architecture = "ARM64 (aarch64)",
            format = "IMG",
            installationMode = InstallationMode.MODE_A_PREINSTALLED,
            sourceName = "Official Debian Release Infrastructure",
            sourceUrl = "https://cloud.debian.org/images/cloud/bookworm/latest/",
            kernelUrl = "https://deb.debian.org/debian/dists/bookworm/main/installer-arm64/current/images/netboot/debian-installer/arm64/linux",
            initramfsUrl = "https://deb.debian.org/debian/dists/bookworm/main/installer-arm64/current/images/netboot/debian-installer/arm64/initrd.gz",
            diskUrl = "https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-generic-arm64.raw",
            expectedKernelSha256 = "84b9c190bb4589c4a9527e3191fec051f9f115e88f0a3e8afae96ba0dfb4dfef",
            expectedInitramfsSha256 = "3b451f2098ae2e3ccf76b618ba742184d795393c25d6b229130ab106bc33ffa5",
            downloadSizeBytes = 70L * 1024L * 1024L,
            recommendedRamMb = 1024,
            minimumStorageGb = 8,
            defaultKernelCmdline = "console=ttyAMA0,115200 earlycon=pl011,0x09000000 root=/dev/vda1 rw init=/init",
            consoleDevice = "ttyAMA0 (PL011 UART)",
            defaultUser = "debian",
            defaultPassword = "debian",
            compatibilityStatus = "Verified ARM64 Boot",
            isBootSupported = true,
            licenseName = "DFSG / GPL-2.0",
            licenseUrl = "https://www.debian.org/legal/licenses/",
            copyrightNotice = "© Software in the Public Interest, Inc. Debian is a trademark.",
            notes = "Official Debian 12 (Bookworm) ARM64 Cloud Image. Stable, reliable linux distribution."
        ),
        OSManifest(
            id = "debian-12-iso-arm64",
            name = "Debian 12 ARM64 (Netinst ISO)",
            version = "12.7 (Bookworm)",
            osCategory = "Debian",
            architecture = "ARM64 (aarch64)",
            format = "ISO",
            installationMode = InstallationMode.MODE_B_ISO_INSTALLER,
            sourceName = "Official Debian CD Image Mirror",
            sourceUrl = "https://cdimage.debian.org/debian-cd/current/arm64/iso-cd/",
            diskUrl = "https://cdimage.debian.org/debian-cd/current/arm64/iso-cd/debian-12.7.0-arm64-netinst.iso",
            downloadSizeBytes = 520L * 1024L * 1024L,
            recommendedRamMb = 1024,
            minimumStorageGb = 10,
            defaultKernelCmdline = "console=ttyAMA0,115200 earlycon=pl011,0x09000000",
            consoleDevice = "ttyAMA0 (PL011 UART)",
            defaultUser = "root",
            defaultPassword = "debian",
            compatibilityStatus = "Installer ISO — Mode B Virtual CD-ROM Boot",
            isBootSupported = true,
            licenseName = "DFSG / GPL-2.0",
            licenseUrl = "https://www.debian.org/legal/licenses/",
            copyrightNotice = "© Software in the Public Interest, Inc.",
            notes = "Official Debian 12 Netinstall ISO. Custom base system installer."
        ),

        // --- ALPINE LINUX ---
        OSManifest(
            id = "alpine-3-20-arm64",
            name = "Alpine Linux 3.20 (Virt Cloud)",
            version = "3.20.2 (virt-optimized)",
            osCategory = "Alpine",
            architecture = "ARM64 (aarch64)",
            format = "IMG",
            installationMode = InstallationMode.MODE_A_PREINSTALLED,
            sourceName = "Official Alpine Linux Infrastructure",
            sourceUrl = "https://dl-cdn.alpinelinux.org/alpine/v3.20/releases/aarch64/",
            kernelUrl = "https://dl-cdn.alpinelinux.org/alpine/v3.20/releases/aarch64/netboot/vmlinuz-virt",
            initramfsUrl = "https://dl-cdn.alpinelinux.org/alpine/v3.20/releases/aarch64/netboot/initramfs-virt",
            expectedKernelSha256 = "573d0eb4713fc7b631e7242a95fa9d048c60365993658b24d5106a69d0a0e7f2",
            expectedInitramfsSha256 = "90f5159c2cbf81b5d6ad7b14a314815589a7077d0e8fa4e8aa0403c3fef458ae",
            downloadSizeBytes = 18L * 1024L * 1024L,
            recommendedRamMb = 512,
            minimumStorageGb = 2,
            defaultKernelCmdline = "console=ttyAMA0,115200 earlycon=pl011,0x09000000 rdinit=/init",
            consoleDevice = "ttyAMA0 (PL011 UART)",
            defaultUser = "root",
            defaultPassword = "alpine",
            compatibilityStatus = "Verified Lightweight ARM64 Boot",
            isBootSupported = true,
            licenseName = "GPL-2.0 / MIT",
            licenseUrl = "https://alpinelinux.org/about/",
            copyrightNotice = "© Alpine Linux Development Team.",
            notes = "Ultra-fast musl-libc lightweight virtualized Linux distribution."
        ),

        // --- FEDORA ---
        OSManifest(
            id = "fedora-40-cloud-arm64",
            name = "Fedora Linux 40 (Cloud Image)",
            version = "40.1 (Cloud Edition)",
            osCategory = "Fedora",
            architecture = "ARM64 (aarch64)",
            format = "IMG",
            installationMode = InstallationMode.MODE_A_PREINSTALLED,
            sourceName = "Official Fedora Project Infrastructure",
            sourceUrl = "https://download.fedoraproject.org/pub/fedora/linux/releases/40/Cloud/aarch64/images/",
            diskUrl = "https://download.fedoraproject.org/pub/fedora/linux/releases/40/Cloud/aarch64/images/Fedora-Cloud-Base-Generic-40-1.14.aarch64.raw.xz",
            downloadSizeBytes = 380L * 1024L * 1024L,
            recommendedRamMb = 2048,
            minimumStorageGb = 16,
            defaultKernelCmdline = "console=ttyAMA0,115200 root=/dev/vda1 rw earlycon=pl011,0x09000000 init=/init",
            consoleDevice = "ttyAMA0 (PL011 UART)",
            defaultUser = "fedora",
            defaultPassword = "fedora",
            compatibilityStatus = "Pre-installed Cloud Image — Verified ARM64 Boot",
            isBootSupported = true,
            licenseName = "GPL-3.0 / Red Hat License",
            licenseUrl = "https://fedoraproject.org/wiki/Licensing:Main",
            copyrightNotice = "© Red Hat, Inc. and Fedora Project.",
            notes = "Official Fedora 40 ARM64 Cloud Image with RPM/dnf package manager."
        ),

        // --- ALMALINUX (RHEL-compatible) ---
        OSManifest(
            id = "almalinux-9-cloud-arm64",
            name = "AlmaLinux 9 (Enterprise Cloud)",
            version = "9.4 (Enterprise Linux)",
            osCategory = "AlmaLinux",
            architecture = "ARM64 (aarch64)",
            format = "IMG",
            installationMode = InstallationMode.MODE_A_PREINSTALLED,
            sourceName = "Official AlmaLinux OS Foundation",
            sourceUrl = "https://repo.almalinux.org/almalinux/9/cloud/aarch64/images/",
            diskUrl = "https://repo.almalinux.org/almalinux/9/cloud/aarch64/images/AlmaLinux-9-GenericCloud-latest.aarch64.raw",
            downloadSizeBytes = 420L * 1024L * 1024L,
            recommendedRamMb = 2048,
            minimumStorageGb = 16,
            defaultKernelCmdline = "console=ttyAMA0,115200 root=/dev/vda1 rw earlycon=pl011,0x09000000 init=/init",
            consoleDevice = "ttyAMA0 (PL011 UART)",
            defaultUser = "almalinux",
            defaultPassword = "almalinux",
            compatibilityStatus = "Pre-installed Cloud Image — Verified ARM64 Boot",
            isBootSupported = true,
            licenseName = "GPL-2.0 / Open Source",
            licenseUrl = "https://almalinux.org/about/",
            copyrightNotice = "© AlmaLinux OS Foundation.",
            notes = "RHEL-compatible enterprise Linux production platform."
        ),

        // --- ROCKY LINUX (RHEL-compatible) ---
        OSManifest(
            id = "rocky-9-cloud-arm64",
            name = "Rocky Linux 9 (Enterprise Cloud)",
            version = "9.4 (Blue Onyx)",
            osCategory = "Rocky Linux",
            architecture = "ARM64 (aarch64)",
            format = "IMG",
            installationMode = InstallationMode.MODE_A_PREINSTALLED,
            sourceName = "Official Rocky Enterprise Software Foundation",
            sourceUrl = "https://dl.rockylinux.org/pub/rocky/9/images/aarch64/",
            diskUrl = "https://dl.rockylinux.org/pub/rocky/9/images/aarch64/Rocky-9-GenericCloud-Base.aarch64.raw.xz",
            downloadSizeBytes = 410L * 1024L * 1024L,
            recommendedRamMb = 2048,
            minimumStorageGb = 16,
            defaultKernelCmdline = "console=ttyAMA0,115200 root=/dev/vda1 rw earlycon=pl011,0x09000000 init=/init",
            consoleDevice = "ttyAMA0 (PL011 UART)",
            defaultUser = "rocky",
            defaultPassword = "rocky",
            compatibilityStatus = "Pre-installed Cloud Image — Verified ARM64 Boot",
            isBootSupported = true,
            licenseName = "GPL-2.0 / BSD 3-Clause",
            licenseUrl = "https://rockylinux.org/about",
            copyrightNotice = "© Rocky Enterprise Software Foundation.",
            notes = "Community enterprise operating system downstream from RHEL."
        ),

        // --- ARCH LINUX ---
        OSManifest(
            id = "archlinux-arm64",
            name = "Arch Linux ARM (Generic AArch64)",
            version = "Rolling Release",
            osCategory = "Arch Linux",
            architecture = "ARM64 (aarch64)",
            format = "IMG",
            installationMode = InstallationMode.MODE_A_PREINSTALLED,
            sourceName = "Official Arch Linux ARM Project",
            sourceUrl = "https://archlinuxarm.org/platforms/armv8/generic",
            diskUrl = "https://os.archlinuxarm.org/os/ArchLinuxARM-aarch64-latest.tar.gz",
            downloadSizeBytes = 310L * 1024L * 1024L,
            recommendedRamMb = 1024,
            minimumStorageGb = 8,
            defaultKernelCmdline = "console=ttyAMA0,115200 root=/dev/vda1 rw earlycon=pl011,0x09000000 init=/init",
            consoleDevice = "ttyAMA0 (PL011 UART)",
            defaultUser = "alarm",
            defaultPassword = "alarm",
            compatibilityStatus = "Rolling Release — Verified ARM64 Boot",
            isBootSupported = true,
            licenseName = "GPL-2.0 / Arch Linux License",
            licenseUrl = "https://archlinuxarm.org/about",
            copyrightNotice = "© Arch Linux ARM Project.",
            notes = "Simplicity and rolling release Linux system for ARM64 with pacman package manager."
        ),

        // --- OPENSUSE ---
        OSManifest(
            id = "opensuse-leap-arm64",
            name = "openSUSE Leap 15.6 (JeOS Cloud)",
            version = "15.6 (Enterprise Base)",
            osCategory = "openSUSE",
            architecture = "ARM64 (aarch64)",
            format = "IMG",
            installationMode = InstallationMode.MODE_A_PREINSTALLED,
            sourceName = "Official openSUSE Mirror Infrastructure",
            sourceUrl = "https://download.opensuse.org/distribution/leap/15.6/appliances/",
            diskUrl = "https://download.opensuse.org/distribution/leap/15.6/appliances/openSUSE-Leap-15.6-Minimal-VM.aarch64-Cloud.raw.xz",
            downloadSizeBytes = 280L * 1024L * 1024L,
            recommendedRamMb = 2048,
            minimumStorageGb = 12,
            defaultKernelCmdline = "console=ttyAMA0,115200 root=/dev/vda1 rw earlycon=pl011,0x09000000 init=/init",
            consoleDevice = "ttyAMA0 (PL011 UART)",
            defaultUser = "root",
            defaultPassword = "opensuse",
            compatibilityStatus = "Pre-installed JeOS — Verified ARM64 Boot",
            isBootSupported = true,
            licenseName = "GPL-2.0 / openSUSE License",
            licenseUrl = "https://en.opensuse.org/Portal:Licensing",
            copyrightNotice = "© SUSE LLC and openSUSE Project.",
            notes = "openSUSE Just Enough OS cloud image featuring zypper package manager."
        )
    )

    fun getManifestById(id: String): OSManifest? {
        return OFFICIAL_MANIFESTS.find { it.id == id }
    }

    fun getManifestsByCategory(category: String): List<OSManifest> {
        return OFFICIAL_MANIFESTS.filter { it.osCategory.equals(category, ignoreCase = true) }
    }
}
